local_costmap:
   global_frame: scarab40/map
   robot_base_frame: base_footprint
   update_frequency: 30.0
   publish_frequency: 30.0
   width: 10.0
   height: 10.0
   resolution: 0.05
   static_map: true
   rolling_window: true
