servo_tilt_controller:
  controller:
    package: dynamixel_controllers
    module: joint_position_controller
    type: JointPositionController
  joint_name: camera_joint
  joint_speed: 1
  motor:
    id: 1
    init: 511
    min: 254
    max: 796
